name: ci

on:
  push:
    branches:
      - 'provisioning-production-iac'
    tags-ignore:
      - '*'

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make kdy file
        run: echo "${{ secrets.DEPLOY_SSH_KEY }}" > ./keyfile && chmod 400 ./keyfile

      - name: ssh test
        run: ssh -oStrictHostKeyChecking=no -p ${{ secrets.DEPLOY_SSH_PORT }} -i ./keyfile ${{ secrets.DEPLOY_SSH_USER_AND_HOST }} /var/opt/youkai-server/deploy.sh 0.0.1

      - name: delete file
        run: rm ./keyfile
