name: ci

on:
  push:
    branches:
      - 'provisioning-production-iac'
    tags-ignore:
      - '*'

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ssh test
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ./keyfile
          ssh -p ${{ secrets.DEPLOY_SSH_PORT }} -i ./keyfile ${{ secrets.DEPLOY_SSH_USER_AND_HOST }} /var/opt/youkai-server/deploy.sh
          rm ./keyfile
